#pragma once
#include "radixSort.h"
#include"merge_sort.h"
#include"selection_sort.h"
#include"bubble_sort.h"
#include"flashSort.h"
#include"quick_sort.h"
#include"shell_sort.h"
#include"insertionSort.h"
#include"heap_sort.h"
#include"shakerSort.h"
#include"binaryInsertionSort.h"
